name: iac-security-action

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build-image:
    runs-on: ubuntu-latest
    name: Docker build

    steps:
      - name: checkout
        uses: actions/checkout@v4
       
      - name: docker build
        uses: docker/build-push-action@v6
        with:
          context: ./modules/module-2/src
          file: ./modules/module-2/src/Dockerfile
          push: false

  veracode_iac_secrets-scan:
    runs-on: ubuntu-latest
    name: Veracode Container/IaC/Secrets scan

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Veracode Container/IaC/Secrets action step
        uses: veracode/container_iac_secrets_scanning@v1.0.1
        with:
          vid: ${{ secrets.VERACODE_API_KEY_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY_SECRET }}
          command: "scan" 
          type: "directory"
          source: "./"
          format: "table"
          debug: false
          fail_build: false

  veracode-container_image-scan:
    runs-on: ubuntu-latest
    needs: [build-image]
    name: Veracode Container Image scan

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Veracode Container/IaC/Secrets action step
        uses: veracode/container_iac_secrets_scanning@v1.0.1
        with:
          vid: ${{ secrets.VERACODE_API_KEY_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY_SECRET }}
          command: "scan" 
          type: "image"
          source: "${{ github.repository_owner }}/app:latest"
          format: "table"
          debug: false
          fail_build: false

  veracode-container_iac_secrets-sbom-cyclonedx:
    runs-on: ubuntu-latest
    needs: [build-image, veracode-container_image-scan, veracode_iac_secrets-scan]
    name: Veracode Container/IaC/Secrets SBOM CycloneDX

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Veracode Container/IaC/Secrets action step
        uses: veracode/container_iac_secrets_scanning@v1.0.1
        with:
          vid: ${{ secrets.VID }}
          vkey: ${{ secrets.VKEY }}
          command: "sbom" 
          type: "directory"
          source: "./"
          format: "cyclonedx-json"
          debug: false
          fail_build: false

  veracode-container_iac_secrets-sbom-sdpdx:
    runs-on: ubuntu-latest
    needs: [build-image, veracode-container_image-scan, veracode_iac_secrets-scan]
    name: Veracode Container/IaC/Secrets SBOM SPDX

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Veracode Container/IaC/Secrets action step
        uses: veracode/container_iac_secrets_scanning@v1.0.1
        with:
          vid: ${{ secrets.VID }}
          vkey: ${{ secrets.VKEY }}
          command: "sbom" 
          type: "directory"
          source: "./"
          format: "spdx-json"
          debug: false
          fail_build: false